Add a static file for target images / cibles (Fix #11)
ddaleteam/API pull request #15
Opened 2019-06-13 10:56 UTC by Inao0

2019-06-13 16:16 UTC, Wall-E-76 commented on app/main.py
> +app.mount("/calques", StaticFiles(directory="calques"), name="calque")
Il manque un s au troisième calque, est-ce normal?

2019-06-13 16:18 UTC, eve-le-guillou requested changes
Il manque un s au troisième calque, est-ce normal? (ligne 19)

2019-06-17 12:17 UTC, Inao0 commented
Trying to change in order to merge into develop instead of master

2019-06-17 12:20 UTC, Inao0 commented
> )

Fixed

2019-06-17 12:30 UTC, Haransis reviewed
:100:

2019-06-17 12:31 UTC, merged